-- ============================================
-- Script: 03_insert_data.sql
-- Description: Inserts synthetic data for the
--              Service Orders POC
-- Author: Iago Seara Vicente
-- ============================================

-- CATEGORIES
INSERT INTO CATEGORIES (NAME, SLA_DAYS) VALUES ('Maintenance', 3);
INSERT INTO CATEGORIES (NAME, SLA_DAYS) VALUES ('Repair', 2);
INSERT INTO CATEGORIES (NAME, SLA_DAYS) VALUES ('Installation', 5);
INSERT INTO CATEGORIES (NAME, SLA_DAYS) VALUES ('Consulting', 7);
INSERT INTO CATEGORIES (NAME, SLA_DAYS) VALUES ('Inspection', 1);

-- EMPLOYEES
INSERT INTO EMPLOYEES (NAME, DEPARTMENT, ROLE, EMAIL, HIRE_DATE, SALARY, LOCATION) VALUES ('James Wilson', 'Operations', 'Technician', 'j.wilson@svcorders.com', DATE '2019-03-15', 42000, 'Geneva');
INSERT INTO EMPLOYEES (NAME, DEPARTMENT, ROLE, EMAIL, HIRE_DATE, SALARY, LOCATION) VALUES ('Sarah Connor', 'Operations', 'Technician', 's.connor@svcorders.com', DATE '2020-07-01', 44000, 'Geneva');
INSERT INTO EMPLOYEES (NAME, DEPARTMENT, ROLE, EMAIL, HIRE_DATE, SALARY, LOCATION) VALUES ('Mark Davis', 'Operations', 'Manager', 'm.davis@svcorders.com', DATE '2017-01-10', 65000, 'Geneva');
INSERT INTO EMPLOYEES (NAME, DEPARTMENT, ROLE, EMAIL, HIRE_DATE, SALARY, LOCATION) VALUES ('Laura Martinez', 'Support', 'Analyst', 'l.martinez@svcorders.com', DATE '2021-09-20', 38000, 'Zurich');
INSERT INTO EMPLOYEES (NAME, DEPARTMENT, ROLE, EMAIL, HIRE_DATE, SALARY, LOCATION) VALUES ('Tom Hanks', 'Support', 'Technician', 't.hanks@svcorders.com', DATE '2018-05-05', 41000, 'Zurich');
INSERT INTO EMPLOYEES (NAME, DEPARTMENT, ROLE, EMAIL, HIRE_DATE, SALARY, LOCATION) VALUES ('Anna Schmidt', 'Engineering', 'Analyst', 'a.schmidt@svcorders.com', DATE '2022-02-14', 46000, 'Geneva');
INSERT INTO EMPLOYEES (NAME, DEPARTMENT, ROLE, EMAIL, HIRE_DATE, SALARY, LOCATION) VALUES ('Carlos Lopez', 'Engineering', 'Technician', 'c.lopez@svcorders.com', DATE '2020-11-30', 43000, 'Madrid');
INSERT INTO EMPLOYEES (NAME, DEPARTMENT, ROLE, EMAIL, HIRE_DATE, SALARY, LOCATION) VALUES ('Emma Brown', 'Operations', 'Manager', 'e.brown@svcorders.com', DATE '2016-06-22', 68000, 'Geneva');

-- CUSTOMERS
INSERT INTO CUSTOMERS (NAME, COUNTRY, CITY, SEGMENT, CONTRACT_TYPE, REGISTRATION_DATE) VALUES ('Acme Industries', 'Switzerland', 'Geneva', 'Industrial', 'Premium', DATE '2018-01-15');
INSERT INTO CUSTOMERS (NAME, COUNTRY, CITY, SEGMENT, CONTRACT_TYPE, REGISTRATION_DATE) VALUES ('TechCorp SA', 'Switzerland', 'Zurich', 'Commercial', 'Standard', DATE '2019-03-20');
INSERT INTO CUSTOMERS (NAME, COUNTRY, CITY, SEGMENT, CONTRACT_TYPE, REGISTRATION_DATE) VALUES ('Global Systems', 'France', 'Paris', 'Industrial', 'Premium', DATE '2017-07-10');
INSERT INTO CUSTOMERS (NAME, COUNTRY, CITY, SEGMENT, CONTRACT_TYPE, REGISTRATION_DATE) VALUES ('Nordic Labs', 'Sweden', 'Stockholm', 'Commercial', 'Basic', DATE '2020-05-05');
INSERT INTO CUSTOMERS (NAME, COUNTRY, CITY, SEGMENT, CONTRACT_TYPE, REGISTRATION_DATE) VALUES ('Iberian Tech', 'Spain', 'Madrid', 'Industrial', 'Standard', DATE '2021-02-28');
INSERT INTO CUSTOMERS (NAME, COUNTRY, CITY, SEGMENT, CONTRACT_TYPE, REGISTRATION_DATE) VALUES ('Alpine Research', 'Switzerland', 'Bern', 'Commercial', 'Premium', DATE '2019-11-12');
INSERT INTO CUSTOMERS (NAME, COUNTRY, CITY, SEGMENT, CONTRACT_TYPE, REGISTRATION_DATE) VALUES ('Euro Dynamics', 'Germany', 'Berlin', 'Industrial', 'Premium', DATE '2018-08-30');
INSERT INTO CUSTOMERS (NAME, COUNTRY, CITY, SEGMENT, CONTRACT_TYPE, REGISTRATION_DATE) VALUES ('Pacific Solutions', 'Japan', 'Tokyo', 'Commercial', 'Standard', DATE '2022-01-01');

-- SERVICE_ORDERS
INSERT INTO SERVICE_ORDERS (CUSTOMER_ID, EMPLOYEE_ID, CATEGORY_ID, ORDER_DATE, STATUS, PRIORITY, RESOLUTION_DATE, AMOUNT, ESTIMATED_HOURS, ACTUAL_HOURS, SATISFACTION_SCORE, COMMENTS) VALUES (1, 1, 1, DATE '2024-01-10', 'closed', 'high', DATE '2024-01-12', 1500, 8, 9, 4, 'Resolved within SLA');
INSERT INTO SERVICE_ORDERS (CUSTOMER_ID, EMPLOYEE_ID, CATEGORY_ID, ORDER_DATE, STATUS, PRIORITY, RESOLUTION_DATE, AMOUNT, ESTIMATED_HOURS, ACTUAL_HOURS, SATISFACTION_SCORE, COMMENTS) VALUES (2, 2, 2, DATE '2024-01-15', 'closed', 'medium', DATE '2024-01-18', 800, 5, 6, 3, 'Minor delay');
INSERT INTO SERVICE_ORDERS (CUSTOMER_ID, EMPLOYEE_ID, CATEGORY_ID, ORDER_DATE, STATUS, PRIORITY, RESOLUTION_DATE, AMOUNT, ESTIMATED_HOURS, ACTUAL_HOURS, SATISFACTION_SCORE, COMMENTS) VALUES (3, 3, 3, DATE '2024-02-01', 'closed', 'low', DATE '2024-02-05', 3200, 16, 14, 5, 'Completed ahead of schedule');
INSERT INTO SERVICE_ORDERS (CUSTOMER_ID, EMPLOYEE_ID, CATEGORY_ID, ORDER_DATE, STATUS, PRIORITY, RESOLUTION_DATE, AMOUNT, ESTIMATED_HOURS, ACTUAL_HOURS, SATISFACTION_SCORE, COMMENTS) VALUES (4, 4, 4, DATE '2024-02-10', 'closed', 'medium', DATE '2024-02-20', 2100, 12, 15, 2, 'SLA breached');
INSERT INTO SERVICE_ORDERS (CUSTOMER_ID, EMPLOYEE_ID, CATEGORY_ID, ORDER_DATE, STATUS, PRIORITY, RESOLUTION_DATE, AMOUNT, ESTIMATED_HOURS, ACTUAL_HOURS, SATISFACTION_SCORE, COMMENTS) VALUES (5, 5, 5, DATE '2024-03-01', 'closed', 'critical', DATE '2024-03-02', 950, 4, 4, 5, 'Excellent service');
INSERT INTO SERVICE_ORDERS (CUSTOMER_ID, EMPLOYEE_ID, CATEGORY_ID, ORDER_DATE, STATUS, PRIORITY, RESOLUTION_DATE, AMOUNT, ESTIMATED_HOURS, ACTUAL_HOURS, SATISFACTION_SCORE, COMMENTS) VALUES (6, 6, 1, DATE '2024-03-15', 'in_progress', 'high', NULL, 1800, 10, 7, NULL, 'In progress');
INSERT INTO SERVICE_ORDERS (CUSTOMER_ID, EMPLOYEE_ID, CATEGORY_ID, ORDER_DATE, STATUS, PRIORITY, RESOLUTION_DATE, AMOUNT, ESTIMATED_HOURS, ACTUAL_HOURS, SATISFACTION_SCORE, COMMENTS) VALUES (7, 7, 2, DATE '2024-03-20', 'open', 'medium', NULL, 600, 3, NULL, NULL, 'Pending assignment');
INSERT INTO SERVICE_ORDERS (CUSTOMER_ID, EMPLOYEE_ID, CATEGORY_ID, ORDER_DATE, STATUS, PRIORITY, RESOLUTION_DATE, AMOUNT, ESTIMATED_HOURS, ACTUAL_HOURS, SATISFACTION_SCORE, COMMENTS) VALUES (8, 8, 3, DATE '2024-04-01', 'open', 'low', NULL, 4500, 20, NULL, NULL, 'Large installation project');
INSERT INTO SERVICE_ORDERS (CUSTOMER_ID, EMPLOYEE_ID, CATEGORY_ID, ORDER_DATE, STATUS, PRIORITY, RESOLUTION_DATE, AMOUNT, ESTIMATED_HOURS, ACTUAL_HOURS, SATISFACTION_SCORE, COMMENTS) VALUES (1, 2, 4, DATE '2024-04-05', 'closed', 'high', DATE '2024-04-08', 1200, 6, 7, 4, 'Good outcome');
INSERT INTO SERVICE_ORDERS (CUSTOMER_ID, EMPLOYEE_ID, CATEGORY_ID, ORDER_DATE, STATUS, PRIORITY, RESOLUTION_DATE, AMOUNT, ESTIMATED_HOURS, ACTUAL_HOURS, SATISFACTION_SCORE, COMMENTS) VALUES (3, 1, 5, DATE '2024-04-10', 'closed', 'critical', DATE '2024-04-11', 750, 3, 3, 5, 'Perfect resolution');

-- ORDER_HISTORY
INSERT INTO ORDER_HISTORY (ORDER_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGE_DATE, NOTES) VALUES (1, 'open', 'in_progress', 1, DATE '2024-01-10', 'Technician assigned');
INSERT INTO ORDER_HISTORY (ORDER_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGE_DATE, NOTES) VALUES (1, 'in_progress', 'closed', 1, DATE '2024-01-12', 'Issue resolved');
INSERT INTO ORDER_HISTORY (ORDER_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGE_DATE, NOTES) VALUES (2, 'open', 'in_progress', 2, DATE '2024-01-15', 'Technician assigned');
INSERT INTO ORDER_HISTORY (ORDER_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGE_DATE, NOTES) VALUES (2, 'in_progress', 'closed', 2, DATE '2024-01-18', 'Issue resolved');
INSERT INTO ORDER_HISTORY (ORDER_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGE_DATE, NOTES) VALUES (4, 'open', 'in_progress', 4, DATE '2024-02-10', 'Analyst assigned');
INSERT INTO ORDER_HISTORY (ORDER_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGE_DATE, NOTES) VALUES (4, 'in_progress', 'closed', 4, DATE '2024-02-20', 'Consulting completed late');
INSERT INTO ORDER_HISTORY (ORDER_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGE_DATE, NOTES) VALUES (6, 'open', 'in_progress', 6, DATE '2024-03-15', 'Work started');

COMMIT;