-- ============================================
-- Script: 02_create_tables.sql
-- Description: Creates the source tables for
--              the Service Orders POC
-- Author: Iago Seara Vicente
-- ============================================

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME           VARCHAR2(100) NOT NULL,
    DEPARTMENT     VARCHAR2(50),
    ROLE           VARCHAR2(50),
    EMAIL          VARCHAR2(100),
    HIRE_DATE      DATE,
    SALARY         NUMBER(10,2),
    LOCATION       VARCHAR2(50)
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME              VARCHAR2(100) NOT NULL,
    COUNTRY           VARCHAR2(50),
    CITY              VARCHAR2(50),
    SEGMENT           VARCHAR2(30),
    CONTRACT_TYPE     VARCHAR2(20),
    REGISTRATION_DATE DATE
);

CREATE TABLE CATEGORIES (
    CATEGORY_ID  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME         VARCHAR2(50) NOT NULL,
    SLA_DAYS     NUMBER
);

CREATE TABLE SERVICE_ORDERS (
    ORDER_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID        NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID),
    EMPLOYEE_ID        NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
    CATEGORY_ID        NUMBER REFERENCES CATEGORIES(CATEGORY_ID),
    ORDER_DATE         DATE NOT NULL,
    STATUS             VARCHAR2(20),
    PRIORITY           VARCHAR2(20),
    RESOLUTION_DATE    DATE,
    AMOUNT             NUMBER(10,2),
    ESTIMATED_HOURS    NUMBER(5,2),
    ACTUAL_HOURS       NUMBER(5,2),
    SATISFACTION_SCORE NUMBER(2),
    COMMENTS           VARCHAR2(500)
);

CREATE TABLE ORDER_HISTORY (
    HISTORY_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_ID     NUMBER REFERENCES SERVICE_ORDERS(ORDER_ID),
    OLD_STATUS   VARCHAR2(20),
    NEW_STATUS   VARCHAR2(20),
    CHANGED_BY   NUMBER REFERENCES EMPLOYEES(EMPLOYEE_ID),
    CHANGE_DATE  DATE,
    NOTES        VARCHAR2(500)
);